using System;
using Cade.Common.Interfaces;

namespace Cade.DMG
{
	public static class DmgBuilderExtension
	{
        /// <summary>
        /// Initializes Chip8 Cade extension
        /// </summary>
        /// <param name="mauiAppBuilder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
        /// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="Cade.Chip8"/></returns>
        public static MauiAppBuilder UseDmgExtension(this MauiAppBuilder mauiAppBuilder)
        {
            mauiAppBuilder.Services.AddScoped<CadeExtension, GbExtension>();

            return mauiAppBuilder;
        }
    }
}

