# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      run_full_cpu_tests:
        description: 'Run full CPU tests (set to true to run all CPU tests)'
        required: false
        default: 'false'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2.3.0
      with:
        swift-version: '6.1.0'
    - name: Download GameBoy Test ROMs
      run: bash scripts/DownloadTestROMs.sh
    - name: Build
      run: swift build

    # Run full test suite if run_full_cpu_tests is true (set by workflow_dispatch or by default for main branch events)
    - name: Run full test suite
      if: ${{ github.event.inputs.run_full_cpu_tests == 'true' || github.ref == 'refs/heads/main' }}
      run: swift test

    # Otherwise, run only integration tests
    - name: Run test ROM integration tests only
      if: ${{ github.event.inputs.run_full_cpu_tests != 'true' && github.ref != 'refs/heads/main' }}
      run: swift test --filter TestROMIntegrationTests
